### ISSUE TITLE
Flagged by Kaspersky Total Security 2019

### ISSUE THREAD

**Issue by SW1FT** [SrKomodo/shadowfox-updater#12]
![vs](https://user-images.githubusercontent.com/6627739/41378739-ecb44a0e-6f57-11e8-93e1-066c89241f90.png)

**Comment by SrKomodo** [comment]
There are several reasons why this might be happening:
1. Windows executables need to be "signed" by a certificate authority so that Windows considers them "safe". If the program isn't signed, Windows defaults to warning you about the program possibly making bad things, even if it doesn't. I guess that Kaspersky automatically detects executables that aren't signed and flags them as viruses
2. Windows scans the file names of executables, and if it thinks it might be a setup-like program, it defaults to ask for admin rights (you can read more about this in this [other issue](https://github.com/overdodactyl/ShadowFox/issues/132)). Maybe this somehow triggers Kaspersky?
3. Maybe there is some other reason why Kaspersky flags it as a virus, but i wouldn't know what it is.

I can assure you that the program isn't a virus, and because it's open source you are completely free to check the source code and verify that nothing sketchy is going on. I would add the folder you have the updater on to Kaspersky's exclusion list to fix the problem.
