### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by igormap42** [SrKomodo/shadowfox-updater#15]
Some anti-viruses detects a Trojan inside:
https://www.virustotal.com/#/file/2498d0157ab1cfea942364bbb31aa5ac688599a8f33fc712870936d592bc59db/detection

**Comment by SrKomodo** [comment]
This is essentially the same as #12 so I'm just going to copy paste the answer i gave there:

There are several reasons why this might be happening:
1. Windows executables need to be "signed" by a certificate authority so that Windows considers them "safe". If the program isn't signed, Windows defaults to warning you about the program possibly making bad things, even if it doesn't. I guess that the antivirus automatically detects executables that aren't signed and flags them as viruses
2. Windows scans the file names of executables, and if it thinks it might be a setup-like program, it defaults to ask for admin rights (you can read more about this in this [other issue](https://github.com/overdodactyl/ShadowFox/issues/132)). Maybe this somehow triggers the antivirus?
3. Maybe there is some other reason why the antivirus flags it as a virus, but i wouldn't know what it is.

I can assure you that the program isn't a virus, and because it's open source you are completely free to check the source code and verify that nothing sketchy is going on.

**Comment by SrKomodo** [comment]
The latest version now has an embedded manifest file, and now only [one antivirus flags it as a virus](https://www.virustotal.com/#/file/c59c9bfe45e88bec84901d702e1a8cdfaa42585abe1fcbb7da1f7d85b047e77e/detection)

**Comment by igormap42** [comment]
Thanks
