### ISSUE TITLE
Virus/Malware detected

### ISSUE THREAD

**Issue by EstherMoellman** [SrKomodo/shadowfox-updater#16]
Just to inform you that v1.5.9 appears with 10 detections at VirusTotal. I know that might be false positives, but at each update, the number of detections increases.

https://www.virustotal.com/#/file/e819634bd1c6f8f3d590de520d6e254b38416f2c35c339722446626f90c5c91c/detection

**Comment by SrKomodo** [comment]
That is really weird, I literally didn't change any code in the latest few updates, but now it has way more false positives than before.

back in #15 we had 13 detections, then that went down to 1 once i started embedding manifest files on the executables. Now it appears to be back in 13, so we are back in square one.

At first i thought this would be because the new build system somehow broke the way windows manifest files are injected, but i just checked and the manifests are being correctly embedded

I am honestly completely stumped as to why this could be happening.

**Comment by SrKomodo** [comment]
One detail that i did realize is that the older versions that don't get flagged are a lot heavier than the new ones, and contain way more sections, so the issue might be in the compiler itself (for comparison [old](https://www.virustotal.com/#/file/c59c9bfe45e88bec84901d702e1a8cdfaa42585abe1fcbb7da1f7d85b047e77e/details) vs [new](https://www.virustotal.com/#/file/e819634bd1c6f8f3d590de520d6e254b38416f2c35c339722446626f90c5c91c/details)).

**Comment by EstherMoellman** [comment]
Perhaps a temporary workaround for the issue, until it is solved completely, could be to add a comment in each version, alerting users about false-positives.
