### ISSUE TITLE
Waterfox 68 support

### ISSUE THREAD

**Issue by tycrek** [SrKomodo/shadowfox-updater#46]
I use Waterfox which is a fork of regular Firefox but specifically built for 64-bit systems with an emphasis on privacy.

I've used ShadowFox with Waterfox, but I have to:

1. manually backup my default WF profile
2. copy it to the Firefox folder
3. Add an entry in FF `profiles.ini`
4. Run ShadowFox on my WF profile
5. Copy it back to the WF folder

Waterfox also has a `profiles.ini` located here:

> `C:\Users\<username>\AppData\Roaming\Mozilla\Waterfox\`

I was hoping we could add an entry for this directory in `profiles.go` for Waterfox.

Note that Waterfox has two versions: the regular build based off FF 56 (incompatible since it isn't FF Quantum) and a WF Quantum Alpha based off FF 68.

**Comment by SrKomodo** [comment]
You can move the ShadowFox executable into `C:\Users\<username>\AppData\Roaming\Mozilla\Waterfox` and it should recognize the `profiles.ini` file. Given that there are two versions of Waterfox as you just said i would be hesitant to support it, because i can imagine a bunch of people opening issues about shadowfox not working when they are using the old pre-quantum version.

**Comment by tycrek** [comment]
That's a fair point on the two versions opening issues. I tried it using that method on a VM and it worked as normal.
